// Data contract for the Price History Tracking & Market Trend engine (DXS-97).
// Shared between the AI/Data service (producer) and BackendDev / web / mobile
// consumers. The producer is PriceHistoryService; the consumer-facing endpoint
// is `GET /items/:id/price-history`.

/**
 * How a price-history snapshot was sourced.
 * - `manual`  — user-entered value.
 * - `ai`      — generated by the market-valuation pipeline.
 * - `market`  — sourced from an external/market reference.
 */
export type PriceHistorySource = 'manual' | 'ai' | 'market';

/** A single point in an asset's value time-series. */
export interface PriceHistoryPoint {
  id: string;
  /** Estimated value at `recordedAt`, in `currency`. */
  estimatedValue: number;
  /** ISO 4217 currency code, e.g. "USD". */
  currency: string;
  source: PriceHistorySource;
  /** ISO-8601 timestamp the value was recorded. */
  recordedAt: string;
}

/** Directional indicator for a trend window. */
export type TrendDirection = 'up' | 'flat' | 'down';

/** Standard trailing windows (in days) over which trend is computed. */
export type TrendWindowDays = 30 | 90 | 365;

/**
 * Trend over a trailing window. `percentChange` compares the latest value to
 * the value at the start of the window (see PriceHistoryService for the exact
 * baseline-selection rule). It is `null` only when there is no history at all.
 */
export interface TrendWindow {
  windowDays: TrendWindowDays;
  direction: TrendDirection;
  /** Signed percentage change over the window (e.g. -12.5), or null if no data. */
  percentChange: number | null;
  /** Value at the start of the window (baseline), or null if no data. */
  fromValue: number | null;
  /** Latest recorded value, or null if no data. */
  toValue: number | null;
}

/** Response for `GET /items/:id/price-history`. */
export interface PriceHistoryResponse {
  itemId: string;
  /** Currency of the series (currency of the latest point, defaults to USD). */
  currency: string;
  /** Time-series ordered oldest → newest. */
  points: PriceHistoryPoint[];
  /** Most recent estimated value, or null when there is no history. */
  latestValue: number | null;
  /** Trend over the 30/90/365-day trailing windows. */
  trends: TrendWindow[];
}
