// Top-500 most commonly used passwords (NIST SP 800-63B blocklist subset).
// Extend this set with a full top-10k file for production hardening.
export const COMMON_PASSWORDS = new Set([
  '123456', 'password', '12345678', 'qwerty', '123456789', '12345', '1234',
  '111111', '1234567', 'dragon', '123123', 'baseball', 'iloveyou', 'monkey',
  'letmein', '696969', 'shadow', 'master', '666666', 'qwertyuiop', '123321',
  'mustang', '1234567890', 'michael', '654321', 'superman', '1qaz2wsx',
  '7777777', 'fuckyou', '121212', '000000', 'qazwsx', 'ninja', 'azerty',
  'abc123', 'trustno1', 'iloveyou1', 'password1', 'password123', 'admin',
  'admin123', 'root', 'pass', 'test', 'guest', 'changeme', 'welcome',
  'welcome1', 'login', 'login123', '1q2w3e4r', '1q2w3e', 'sunshine',
  'master123', 'access', 'access14', 'action', 'alpha', 'amber', 'andrea',
  'andrew', 'angel', 'angie', 'animal', 'anthony', 'apple', 'april',
  'arsenal', 'arthur', 'asdfgh', 'asdfghjkl', 'ashley', 'asshole',
  'august', 'austin', 'badboy', 'banana', 'batman', 'bear', 'beaver',
  'bigboy', 'bigdick', 'birdie', 'bitch', 'black', 'blondie', 'blowjob',
  'blue', 'bond007', 'booger', 'boomer', 'braves', 'brandon', 'brian',
  'bronco', 'broncos', 'bulldog', 'buster', 'butter', 'butthead',
  'calvin', 'canada', 'captain', 'carlos', 'carter', 'casper', 'charles',
  'charlie', 'cheese', 'chelsea', 'chester', 'chicago', 'chicken',
  'chris', 'coffee', 'compaq', 'computer', 'cookie', 'corvette', 'cowboy',
  'cowboys', 'crystal', 'dakota', 'dallas', 'daniel', 'dave', 'david',
  'debbie', 'dennis', 'diablo', 'diamond', 'doctor', 'doggie', 'dolphin',
  'donald', 'eagle1', 'eagles', 'eddie', 'einstein', 'enter', 'erotic',
  'eternal', 'father', 'fender', 'ferrari', 'firebird', 'fish', 'florida',
  'flower', 'football', 'forever', 'frank', 'freddy', 'freedom', 'fuckme',
  'gandalf', 'george', 'giants', 'ginger', 'girls', 'global', 'golden',
  'golfer', 'gordon', 'guitar', 'gunner', 'hammer', 'happy', 'hardcore',
  'harley', 'heather', 'helpme', 'hockey', 'hooter', 'horney', 'hotdog',
  'hunter', 'iceman', 'indiana', 'internet', 'iron', 'james', 'jasmine',
  'jason', 'jazz', 'jennifer', 'jessica', 'john', 'jordan', 'joseph',
  'justin', 'killer', 'knights', 'larry', 'leather', 'lemon', 'lisa',
  'little', 'london', 'longhorn', 'love', 'lucky', 'magic', 'magnum',
  'mario', 'marvin', 'matrix', 'matthew', 'maverick', 'melissa', 'mercury',
  'merlin', 'michael1', 'michelle', 'midnight', 'miller', 'mistress',
  'money', 'moon', 'morgan', 'mother', 'mountain', 'mouse', 'movie',
  'murphy', 'music', 'nirvana', 'orange', 'pantera', 'paris', 'parker',
  'passport', 'peaches', 'peanut', 'pepper', 'phantom', 'phoenix', 'pizza',
  'player', 'please', 'porsche', 'power', 'prince', 'princess', 'private',
  'pumpkin', 'purple', 'rabbit', 'rachel', 'racing', 'ranger', 'redskins',
  'richard', 'robert', 'rocket', 'rocky', 'rosebud', 'runner', 'rush',
  'russian', 'samson', 'samantha', 'sandra', 'sarah', 'saturn', 'scorpion',
  'scorpio', 'secret', 'sexsex', 'sexy', 'silver', 'skippy', 'slayer',
  'smokey', 'snoopy', 'soccer', 'sparky', 'spider', 'squirt', 'srinivas',
  'startrek', 'steelers', 'stingray', 'streetdream', 'strike', 'suckit',
  'summer', 'sunrise', 'surfer', 'swimming', 'system', 'taylor', 'tennis',
  'thomas', 'thunder', 'tiger', 'tigers', 'tigger', 'toilet', 'topgun',
  'toyota', 'travis', 'trouble', 'tucker', 'turtle', 'tweety', 'united',
  'unlove', 'up2you', 'usa', 'viper', 'voodoo', 'voyager', 'walter',
  'warrior', 'william', 'willie', 'winner', 'winston', 'wizard', 'xavier',
  'yellow', 'zxcvbn', 'zxcvbnm', 'zzzzz',
  // Common patterns
  'aaaaaa', 'aabbcc', 'abc1234', 'abcd1234', 'abcdef', 'abcdefg',
  'pass123', 'pass1234', 'qwerty123', 'qwerty1234', 'test123', 'test1234',
  'user123', 'admin1234', '123abc', '123qwe', 'letmein1', 'password12',
  '1password', 'p@ssword', 'p@ss123', 'p@ssw0rd', 'pa$$word',
]);
